name: nf1_analysis
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.9
  - umap-learn
  - scikit-posthocs
  - pandas
  - numpy
  - matplotlib
  - scipy
  - pathlib2
  - scikit-learn
  - requests
  - seaborn
  - pip
  # R packages:
  - r-base=4.2.2
  - r-tidyr
  - r-dplyr
  - r-readr
  - r-ggplot2
