name: nf1_analysis
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.9
  - conda-forge::umap-learn
  - conda-forge::scikit-posthocs
  - conda-forge::pandas<2.0
  - conda-forge::numpy
  - conda-forge::matplotlib
  - conda-forge::scipy
  - conda-forge::pathlib2
  - conda-forge::scikit-learn
  - conda-forge::requests
  - conda-forge::seaborn
  - conda-forge::pip
  - conda-forge::ipython
  - conda-forge::notebook
  - conda-forge::py-xgboost-gpu
  # R packages:
  - conda-forge::r-essentials
